### PR TITLE
Added drum samples, fixed up sampler

### PR DESCRIPTION
**Pull request by sphippen**
Drum samples are in.
Samplers use the drum samples by default.
Fixed some sampler bugs.

### CODE REVIEW

**Comment by timgrant** [comment]
Looks really cool. It looks like the samples are exported with the song, but that's only a guess because Chrome barfs when I try to export the song. Is it possible to save only references with the song?

**Comment by sphippen** [comment]
For me, Chrome locks up a bit if I export the song in the console in such a way that it's displayed, e.g. "rhomb.exportSong()". Running "var a = rhomb.exportSong();" in the console works just fine though.

But yes, I can modify it so that the samples aren't exported with the song. For now the drum samples will always be used.

**Comment by timgrant** [comment]
That would be extremely helpful. Being able to view the exported JSON is essential for debugging, and since the samples are fixed for now saving the sample data with the song isn't particularly useful. I imagine it would be easy enough to store the samples on the server, in the way that other assets like images are handled.

**Comment by sphippen** [comment]
Samples aren't saved in the song export now. Some param stuff for the sampler might not work yet, but export/import should be working in a human-readable way.

**Comment by sphippen** [comment]
There were bugs. I fixed them.

**Comment by timgrant** [comment]
This is what we do. This is who we are.

**Comment by sphippen** [comment]
Works for me. Specifically:
1. Run the version of rails on the sp branch (that just has the sp version of rhombus, no Denoto changes other than making every other instrument a drum track)
2. Open the music editor
3. Put some notes in multiple tracks (note that every other track inserted will be drums)
4. Save it
5. Reload it from the track page
For me, it plays back just fine still.
Does it for you?

If you're loading songs created from an old version, they may not play properly, so just test with new tracks.

**Comment by timgrant** [comment]
I just checked out your SoundSplosion branch, and it doesn't seem to be working (for me) as well as develop. When I try to reopen a song in the editor, nothing is loaded correctly (e.g. tracks, instruments), whereas before it was just the sampler instruments that didn't work.

Peep this sequence:

1. Create a new song, and add two tracks with one pattern each.
pre_save

2. Save the song. Song does not play.
track_page

3. Reopen the song in the editor. Seemingly blank, although if you look directly at the song data structure everything looks in order. So, it appears to be some kind of import issue.
post_import

I also notice that the sample data is again being exported with the song, which makes looking at the exported JSON next to impossible.

**Comment by sphippen** [comment]
Well, that's completely my fault. I didn't push my branch on SoundSplosion. Try it now?

**Comment by timgrant** [comment]
Now we're cooking with propane.

**Pull request merged**
