### PR TITLE
Pre-Documentation Refactoring, In Progress

### PR DESCRIPTION
**Pull request by timgrant**
Okay, I have somewhat crudely refactored a few source files. Denoto seems to work, with a few minor adjustments. This is still a work-in-progress.

### CODE REVIEW

**Comment by sphippen** [comment]
Looks like some of these changes break things if there is more than one instance of rhombus - e.g. pattern.js has a top-level variable "thisr" that the functions rely on that is set to whatever the most recently created version of Rhombus is. Still looking through your changes.

**Comment by sphippen** [comment]
Same problem with the track.js changes too, it looks like.

**Comment by sphippen** [comment]
And the others. Looks like most of the hoisting is good though, I'll just have to make some tweaks before this stuff totally works.

**Comment by timgrant** [comment]
For sure. I'm trying to do time.js and it's a real clusterfudge.

**Comment by sphippen** [comment]
I'm just going to go ahead and merge this now. Any bugs that crop up later will be easy fixes, and I can't find any more.

**Pull request merged**
