### PR TITLE
Unhacked instruments a little, made note JSON export stable, graph bug fixes, add effects

### PR DESCRIPTION
**Pull request by sphippen**
The instruments are in their own files now (the wrapped instruments all share a file because that is essentially a single "instrument type" right now). All the code general to all instruments lives in rhombus.instrument.js. Also, I added toJSON on notes so that adding properties won't change how they export.

### CODE REVIEW

**Comment by sphippen** [comment]
9fda215 Now also contains a bug fix

**Comment by sphippen** [comment]
Now it also has many more effects.

**Comment by timgrant** [comment]
Not sure how I missed this. I've just done quite a bit with the HTML layouts for instrument parameters... Hopefully there won't be any conflicts.

**Comment by timgrant** [comment]
Looks good.

**Pull request merged**
